name: Check Renovate Updates

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'docker-compose.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ contains(toLower(github.event.pull_request.user.login), 'renovate') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Trigger Tar Valon Ansible Deploy
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.BOT_GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://git.trez.wtf/api/v1/repos/Trez/rinoa-docker/actions/workflows/renovate-pr-deploy.yml/dispatches" \
            -d "{\"ref\":\"${BRANCH}\"}"