name: Check Renovate Updates

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'docker-compose.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ contains(toLower(github.event.pull_request.user.login), 'renovate') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose config
