name: Gitea Branch PR, SonarQube Analyze, and Merge Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  # Job 1: Check if PR exists and create one if the branch is new
  check-and-create-pr:
    name: Check and Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PR Check
        id: pr-check
        uses: vicamo/gitea-list-pull-requests@v1.0.1
        with:
          repository: ${{ gitea.repository }}
          token: ${{ secrets.BOT_GITEA_TOKEN }}
          state: all
      
      - name: PR list
        uses: magebitcom/list-pr-action@v1.0.0
        id: list-prs
        with:
          base: 'main'
          github-token: ${{ secrets.BOT_GITEA_TOKEN }}
          repo: ${{ gitea.repository }}
          state: open
          hours_old: 0

      - name: Create PR
        if: steps.list-prs.outputs.pr-count == 0
        uses: arifer612/Gitea-PR-action@v1.2.0
        with:
          url: ${{ gitea.server_url }}
          token: ${{ secrets.BOT_GITEA_TOKEN }}
          assignee: ${{ gitea.actor }}