name: Renovate

on:
  schedule:
    - cron: "0/30 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: renovate/renovate:41.97.7-full
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate Run
        run: renovate
        env:
          LOG_LEVEL: "debug"
          RENOVATE_CONFIG_FILE: "${GITHUB_WORKSPACE}/renovate.json"
          RENOVATE_TOKEN: ${ { secrets.RENOVATE_BOT_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
