name: Auto-Unseal for Vault
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/vault-auto-unseal.yml'
  # schedule:
  #   - cron: "30 4 * * *"
jobs:
  auto-unseal:
    name: Unseal Vault
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: ${{ secrets.RINOA_VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_GITEA_TOKEN }}
      VAULT_SHARDS: |
        ${{ secrets.VAULT_UNSEAL_SHARDS }}
      VAULT_NAMESPACE: ""
    steps:
      - name: Cache Vault install
        id: cache-vault
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/vault/1.18.0/x64
          key: vault-${{ runner.os }}-1.18.0
      - name: Install Vault
        uses: cpanato/vault-installer@main
      - name: Unseal Vault
        run: |
          echo ${VAULT_SHARDS}
          echo "Unsealing vault..."
          for vault_shard in $(cat ${VAULT_SHARDS}); do
            vault operator unseal -address=${VAULT_ADDR} -non-interactive "${vault_shard}"
          done