  grafana:
    container_name: grafana
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      TZ: America/New_York
    hostname: Rinoa
    image: grafana/grafana-enterprise:latest
    labels:
      - homepage.group=Infrastructure/App Performance Monitoring
      - homepage.name=Grafana (LGTM)
      - homepage.href=https://mon.${MY_TLD}
      - homepage.description=Monitoring Dashboard for metrics, logs, traces, & profiles
      - homepage.icon=grafana.png
      - homepage.widget.type=grafana
      - homepage.widget.url=http://grafana:3000
      - homepage.widget.username=admin
      - homepage.widget.password=${GRAFANA_ADMIN_PASSWORD}
      - swag=enable
      - swag_proto=http
      - swag_url=mon.${MY_TLD}
      - swag.uptime-kuma.enabled=true
      - swag.uptime-kuma.monitor.url=https://mon.${MY_TLD}
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "3006"
        target: 3000
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
        type: bind
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/data
        target: /var/lib/grafana
        type: volume
        volume: {}
      - bind:
          create_host_path: true
        source: /rinoa-storage
        target: /storage
        type: bind
  grafana-alloy:
    cap_add:
      - SYS_ADMIN
      - SYS_TIME
      - BPF
      - SYSLOG
    command: run --disable-reporting=true --stability.level=public-preview --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    container_name: grafana-alloy
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
    image: grafana/alloy:latest
    labels:
      - homepage.group=Infrastructure/App Performance Monitoring
      - homepage.name=Grafana Alloy
      - homepage.description=Agent for metric/log/trace/profile collection and writing
      - homepage.href=http://192.168.1.254:12345
      - homepage.icon=/icons/grafana-alloy.svg
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "12345"
        target: 12345
    privileged: true
    restart: always
    volumes:
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/alloy/config.alloy
        target: /etc/alloy/config.alloy
        type: volume
        volume: {}
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/alloy/endpoints.json
        target: /etc/alloy/endpoints.json
        type: volume
        volume: {}
      - bind:
          create_host_path: true
        read_only: true
        source: /proc
        target: /host/proc
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /sys
        target: /host/sys
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /
        target: /rootfs
        type: bind
  grafana-loki:
    command: -config.file=/etc/loki/loki-config.yaml
    container_name: grafana-loki
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    image: grafana/loki:latest
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "3100"
        target: 3100
    restart: unless-stopped
    volumes:
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/loki/loki-config.yaml
        target: /etc/loki/loki-config.yaml
        type: volume
        volume: {}
  grafana-mimir:
    command:
      - -ingester.native-histograms-ingestion-enabled=true
      - -config.file=/etc/mimir.yaml
    container_name: grafana-mimir
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    image: grafana/mimir:latest
    labels:
      - homepage.group=Infrastructure/App Performance Monitoring
      - homepage.name=Grafana Mimir
      - homepage.href=http://192.168.1.254:9009
      - homepage.description=Long-term metrics storage
      - homepage.icon=/icons/grafana-mimir.png
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "9009"
        target: 9009
    restart: unless-stopped
    volumes:
      - source: grafana-mimir-data
        target: /data
        type: volume
        volume: {}
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/mimir/mimir.yaml
        target: /etc/mimir.yaml
        type: volume
        volume: {}
  grafana-mimir-memcached:
    container_name: grafana-mimir-memcached
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    environment:
      - MEMCACHED_MEMORY_LIMIT=1g
      - MEMCACHED_THREADS=4
      - MEMCACHED_MAX_CONNECTIONS=2048
      - MEMCACHED_TCP_PORT=11211
      - MEMCACHED_UDP_PORT=11211
    image: memcached
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "11211"
        target: 11211
    restart: unless-stopped
  grafana-pyroscope:
    command:
      - -config.file=/etc/pyroscope.yml
    container_name: grafana-pyroscope
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    image: grafana/pyroscope:latest
    labels:
      - homepage.group=Infrastructure/App Performance Monitoring
      - homepage.name=Grafana Pyroscope
      - homepage.description=Profiling for applications
      - homepage.href=http://192.168.1.254:4040
      - homepage.icon=/icons/grafana-pyroscope.svg
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "4040"
        target: 4040
    restart: unless-stopped
    volumes:
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/pyroscope/config.yaml
        target: /etc/pyroscope.yml
        type: volume
        volume: {}
  grafana-tempo:
    command:
      - -config.file=/etc/tempo.yaml
    container_name: grafana-tempo
    depends_on:
      grafana-alloy:
        condition: service_started
        required: true
    image: grafana/tempo:latest
    networks:
      default: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "14268"
        target: 14268
      - mode: ingress
        protocol: tcp
        published: "3200"
        target: 3200
      - mode: ingress
        protocol: tcp
        published: "9095"
        target: 9095
      - mode: ingress
        protocol: tcp
        published: "4317"
        target: 4317
      - mode: ingress
        protocol: tcp
        published: "4318"
        target: 4318
      - mode: ingress
        protocol: tcp
        published: "9411"
        target: 9411
    restart: unless-stopped
    volumes:
      - source: grafana-tempo-data
        target: /var/tempo
        type: volume
        volume: {}
      - source: ${DOCKER_VOLUME_CONFIG}/grafana/tempo/tempo.yaml
        target: /etc/tempo.yaml
        type: volume
        volume: {}
